include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Style
    prefer_single_quotes: true
    prefer_const_constructors: true
    prefer_const_declarations: true
    unnecessary_brace_in_string_interps: true
    prefer_final_fields: true

    # Error prevention
    avoid_print: true
    no_duplicate_case_values: true

    # Documentation
    public_member_api_docs: true
    package_api_docs: true

    # Code quality
    unused_import: true
    dead_code: true

    # Performance
    avoid_function_calls_in_loop_structure: true

analyzer:
  exclude:
    - build/**
    - .dart_tool/**

  errors:
    public_member_api_docs: warning
    todo: warning
